# Generated by cucumber-sinatra. (2015-10-18 17:09:25 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'webmock/cucumber'

include WebMock::API

Before do
  stub_request(
    :any,
    'http://mm-recruitment-stock-price-api.herokuapp.com/company/AAPL'
    ).to_return(File.new('spec/fixtures/requests/company_without_story_feed.txt'))  
end

Capybara.app = TechTest

class TechTestWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TechTestWorld.new
end
